// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR61Y6B9ciKFLlnkThdmK9S-juPr8_kUs',
    appId: '1:388801923437:web:661ecf745b6faf9e45f264',
    messagingSenderId: '388801923437',
    projectId: 'convert-coin-df5d8',
    authDomain: 'convert-coin-df5d8.firebaseapp.com',
    storageBucket: 'convert-coin-df5d8.appspot.com',
    measurementId: 'G-C60MZHFKRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5UI1s7uteULBwMCBJhEZOoVZyBLeGtpA',
    appId: '1:388801923437:android:fca4b9797757e40b45f264',
    messagingSenderId: '388801923437',
    projectId: 'convert-coin-df5d8',
    storageBucket: 'convert-coin-df5d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbQWR2K4HA9ybD1Pb49jIv18Zg97tty7E',
    appId: '1:388801923437:ios:a56f5771da8861ea45f264',
    messagingSenderId: '388801923437',
    projectId: 'convert-coin-df5d8',
    storageBucket: 'convert-coin-df5d8.appspot.com',
    androidClientId: '388801923437-qcs8b7c3jr08p6mfiga1pfdtsl0sv4v0.apps.googleusercontent.com',
    iosClientId: '388801923437-hogv814h224trpuh2cap68rienc6te3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.convertCoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbQWR2K4HA9ybD1Pb49jIv18Zg97tty7E',
    appId: '1:388801923437:ios:a56f5771da8861ea45f264',
    messagingSenderId: '388801923437',
    projectId: 'convert-coin-df5d8',
    storageBucket: 'convert-coin-df5d8.appspot.com',
    androidClientId: '388801923437-qcs8b7c3jr08p6mfiga1pfdtsl0sv4v0.apps.googleusercontent.com',
    iosClientId: '388801923437-hogv814h224trpuh2cap68rienc6te3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.convertCoin',
  );
}
